# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - master
    - dev

pool:
    vmImage: "ubuntu-latest"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Install Node.js"

    - script: |
          npm install
      displayName: "npm install"

    - script: |
          npm version 0.0.0-canary.$(git rev-parse --short HEAD) --no-git-tag-version
      displayName: "Apply cannary version"
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

    - bash: |
          PACKAGE=$(npm pack);
          echo $PACKAGE;

          echo "##vso[task.setvariable variable=package]$PACKAGE"
      displayName: "npm pack"

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: package"
      inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/$(package)"
          ArtifactName: package

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact: packageJson"
      inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/package.json"
          ArtifactName: packageJson
